// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFflRFAJxIpgEXtQ3cShaBZF5hQZdU08k',
    appId: '1:488075005801:web:f77f6736cbb51302eef7f8',
    messagingSenderId: '488075005801',
    projectId: 'fir-cloud-74b25',
    authDomain: 'fir-cloud-74b25.firebaseapp.com',
    storageBucket: 'fir-cloud-74b25.appspot.com',
    measurementId: 'G-06962ZQNLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALfvjO6Stnt0DaEoyn8zdVmD1xU5jjppo',
    appId: '1:488075005801:android:6e83308a936c8667eef7f8',
    messagingSenderId: '488075005801',
    projectId: 'fir-cloud-74b25',
    storageBucket: 'fir-cloud-74b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-NS5NkQfnogERc7GUP2IAhc_LBaV3yII',
    appId: '1:488075005801:ios:287424b8e3bf4d8eeef7f8',
    messagingSenderId: '488075005801',
    projectId: 'fir-cloud-74b25',
    storageBucket: 'fir-cloud-74b25.appspot.com',
    androidClientId: '488075005801-pdkq671patan876kq27flcopuaui0amc.apps.googleusercontent.com',
    iosClientId: '488075005801-dc7a7sousumhsbi4qma73gtakp12i7sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.uploadFileCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-NS5NkQfnogERc7GUP2IAhc_LBaV3yII',
    appId: '1:488075005801:ios:287424b8e3bf4d8eeef7f8',
    messagingSenderId: '488075005801',
    projectId: 'fir-cloud-74b25',
    storageBucket: 'fir-cloud-74b25.appspot.com',
    androidClientId: '488075005801-pdkq671patan876kq27flcopuaui0amc.apps.googleusercontent.com',
    iosClientId: '488075005801-dc7a7sousumhsbi4qma73gtakp12i7sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.uploadFileCloud',
  );
}
